###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: siwecoswebhostservice-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: siwecoswebhostservice-mailhog
      ports:
        - "4821:8025"

    mariadb:
      image: mariadb:10.1
      container_name: siwecoswebhostservice-mariadb
      working_dir: /application
      volumes:
        - ..:/application
        - ./db:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=siwecos
        - MYSQL_DATABASE=siwecos
        - MYSQL_USER=siwecos
        - MYSQL_PASSWORD=siwecos
      ports:
       - "4822:3306"

    webserver:
      image: nginx:alpine
      container_name: siwecoswebhostservice-webserver
      working_dir: /application
      volumes:
          - ..:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "4820:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: siwecoswebhostservice-php-fpm
      working_dir: /application
      volumes:
        - ..:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

